---
- hosts: cloud
  tasks:
  - name: change apache2 configuration
    lineinfile:
      dest: /home/ubuntu/apache2.conf
      regexp: '(KeepAliveTimeout 5)'
      line: '#\1'
      backrefs: yes
...
